### ISSUE TITLE
SyntaxError: Non-ASCII character

### ISSUE THREAD

**Issue by rosella1234** [samuelstjean/autodmri#9]
File "/usr/local/bin/get_distribution", line 25
SyntaxError: Non-ASCII character '\xe2' in file /usr/local/bin/get_distribution on line 26, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
When using get_distribution I got the aforementioned error. What is a possible solution?
thank you,
Rosella

**Comment by samuelstjean** [comment]
That one is actually my mistake, there was a strange character used for the dash at this line, now it should be fixed in master. 
If it works for you I'll just put up a new release for everyone I guess, thanks for reporting.

**Comment by rosella1234** [comment]
yes it now works
Rosella
